name: Deploy Kotlin WASM to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Kotlin WASM Tests
        run: ./gradlew wasmJsTest

      - name: Build Kotlin WASM Project
        run: ./gradlew wasmJsBrowserDistribution

      - name: Copy files
        run: cp -r assets/* composeApp/build/dist/wasmJs/productionExecutable/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: composeApp/build/dist/wasmJs/productionExecutable

